PID-162
depromeet/InsightOut-Server pull request #163
Opened 2023-06-14 13:04 UTC by PracticeEveryday

## ⛳️ 기능 구현 배경
- ChatGPT 키워드 생성 API
---

## 😤 기능 구현 내용(Optional)

---

## 📭 이슈 번호
#162
---

## 🧐 의견 구하기
- 여기서도 동일하게... 완전히 똑같이 보내야 해서 애 좀 먹었습니다 ㅠ.ㅠ
- 프롬프트가 너무 이쁘지 않아서 generateKeywordPrompt로 함수로 만들어서 뺐는데 피드백 부탁드립니다 ㅎㅎㅎ! 😄 
---

## 🙏 P.S

---

2023-06-14 14:20 UTC, stae1102 requested changes
수정 부탁드립니다~

2023-06-14 14:20 UTC, stae1102 commented on src/apps/server/ai/ai.controller.ts
> +      description: 'ChatGPT 추천 키워드가 생성되었습니다 :)',
얜 왜 md로 안 빼셨나요

2023-06-14 14:20 UTC, stae1102 commented on src/apps/server/ai/ai.controller.ts
> +    summary: '✅ ChatGPT 추천 키워드 생성 프롬프트 API',
얜 왜 md로 안 빼셨나요 2

2023-06-14 16:58 UTC, stae1102 approved these changes

2023-06-14 16:58 UTC, stae1102 commented on src/apps/server/ai/dto/res/promptKeyword.res.dto.ts
> +  @IsArray()
ArrayMaxLength가 아마 있을 거예요!

2023-06-15 23:40 UTC, PracticeEveryday commented on src/apps/server/ai/ai.service.ts
> +      return new PromptKeywordResDto(JSON.parse(result.choices[CHOICES_IDX].message.content));
네네 ㅠㅠ `"["협업","리더십]"` 이렇게 올때가 있더라구요 ㅠㅠ

2023-06-15 23:41 UTC, PracticeEveryday commented on src/apps/server/ai/dto/res/promptKeyword.res.dto.ts
> +  @IsArray()
@ArrayMaxSize(2) 넣어 줬습니다 ㅎ.ㅎ

2023-06-15 23:41 UTC, PracticeEveryday commented on src/apps/server/ai/dto/res/promptKeyword.res.dto.ts
> +  get keywords() {
예리해

2023-06-15 23:58 UTC, PracticeEveryday commented on src/apps/server/ai/ai.controller.ts
> +      description: 'ChatGPT 추천 키워드가 생성되었습니다 :)',
빼써여...

2023-06-15 23:58 UTC, PracticeEveryday commented on src/apps/server/ai/ai.controller.ts
> +    summary: '✅ ChatGPT 추천 키워드 생성 프롬프트 API',
빼써여... 2

2023-06-15 23:59 UTC, PracticeEveryday commented
@stae1102  아픔을 참고... 스쿼시 머지 해버렸다..

2023-06-16 00:02 UTC, closed without merging

2023-06-16 00:05 UTC, PracticeEveryday commented
현재 브랜치에서 분기되어 나온 #163 가 머지되어 close했습니다.

2023-06-16 14:36 UTC, stae1102 commented
> @stae1102 아픔을 참고... 스쿼시 머지 해버렸다..

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ그냥 머지커밋 하셔도 돼요 행복 개발 하시죠