Feature/#235/collection api for ai resume
depromeet/InsightOut-Server pull request #246
Opened 2023-07-02 01:13 UTC by PracticeEveryday

## ⛳️ 기능 구현 배경
- AI 추천 자기소개서 모아보기 API를 구현하였습니다.
---

## 😤 기능 구현 내용(Optional)
- 자기소개서 조회 API에서 추천 자기소개서 키워드 목록이 같이 내려갑니다.
```
{
  "statusCode": 200,
  "success": true,
  "data": {
    "availableKeywords": [
      "협업 능력",
      "빠른 개발 능력",
      "협업능력",
      "빠른 적응력",
      "시간 관리"
    ],
    "AiResumes": [
      {
        "id": 21,
        "content": "```\nSituation: 개발자와 협업 역량을 쌓기 위해 IT 동아리에 들어감\n\nTask: 개발 기간이 짧아서 빠른 기간 내 런칭을 완료해야 했음.\n\nAction: 저는 최근 IT 동아리에서 개발자와 함께 프로젝트를 진행하면서, 대화와 토의를 통해 협업 능력을 쌓았습니다. 특히 개발 기간이 짧았기 때문에, 매일 아침 회의를 통해 상황 파악과 대처 방안 논의를 진행하여 팀원 모두가 각자의 역할을 수행할 수 있도록 돕고, 서로의 진행 상황 파악을 통해 일정을 재조정하기도 했습니다. 게다가, 끊임없이 소통하며 피드백을 지속적으로 주고받음으로써 빠른 개발 능력을 쌓을 수 있었습니다.\n\nResult: 이러한 노력 끝에, 저희 팀은 4개월 만에 출시에 성공하게 되었습니다. 이 경험을 통해 느낀 것은, 소통과 팀워크가 프로젝트 성공의 핵심이라는 것입니다. 빠른 개발 역량은 물론이고, 협업을 통해 팀원 모두가 서로를 지지하고 돕는다면, 어떤 상황에서도 높은 효율과 성과를 이룰 수 있다는 것을 깨닫게 되었습니다.\n\nKeywords: `협업 능력`, `빠른 개발 능력`",
        "updatedAt": "2023-06-18T13:14:03.698Z",
        "AiCapabilities": [
          "협업 능력",
          "빠른 개발 능력"
        ]
      },
      {
        "id": 22,
        "content": "저는 협업능력과 빠른 적응력을 보유한 개발자입니다. 이러한 역량은 저의 경력과 교육, 동아리 경험에서 쌓아왔습니다.\n\n제가 속한 IT 동아리에서는 개발자와 함께 팀을 이루어 프로젝트를 진행하였습니다. 그 중에서도 개발 기간이 짧아서 빠른 기간 내 런칭을 완료해야 하는 과제가 있었습니다. 이를 위해 저는 개인적으로 코딩 능력을 향상시키고, 팀원들과의 소통을 반복해 문제를 해결하였습니다.\n\n이렇게 빠르게 적응한 결과, 4개월 만에 런칭에 성공하였습니다. 이 경험이 저에게는 큰 자신감을 주었으며, 협업 능력을 향상시키는 계기가 되었습니다. 또한, 이 경험으로 인해 불안한 상황에서도 빠르게 대처할 수 있는 능력이 향상되었습니다.\n\n이러한 경험을 바탕으로, 저는 이 회사에서도 협업 능력을 더욱 향상시키고, 빠른 적응력을 바탕으로 빠르게 성과를 내고자 합니다. 이를 위해 끊임없이 노력하고, 팀원들과의 소통을 통해 문제를 해결하며 일하는 모습을 보일 것입니다.",
        "updatedAt": "2023-06-18T14:43:37.870Z",
        "AiCapabilities": [
          "협업능력",
          "빠른 적응력"
        ]
      },
      {
        "id": 23,
        "content": "협업 능력과 시간 관리\n\n저는 IT 동아리에 가입하여, 개발자들과 함께 협업 역량을 쌓았습니다. 제가 참여한 작업의 산출물 중 하나는 개발 기간이 짧아 빠른 기간 내 런칭을 완료해야 했던 프로젝트였습니다. 이를 성공적으로 수행하기 위해서는 협업 능력과 시간 관리 능력 모두가 요구되었습니다.\n\n우선, 저희 팀은 시간 관리를 위한 계획을 세우기 시작했습니다. 개발의 각 단계에 대해 먼저 분석하고, 예상되는 문제점에 대비하여 최대한의 시간을 확보했습니다. 이를 위해 팀원들과 의견을 교환하며 가장 효율적인 방법을 찾아내었습니다.\n\n그 다음으로는 적극적인 협업을 위한 노력이 필요했습니다. 개인적인 일정보다는 팀의 일정을 우선으로 생각하여, 각자 맡은 역할을 수행하는 동시에 다른 팀원의 일도 이해하고 지원해주었습니다. 또한, 업무 내용에 대한 상호 피드백을 통해 서로의 역할에 대한 이해도를 높였습니다.\n\n위와 같은 노력으로 인해, 저희 팀은 개발 기간이 짧은 동안에도 원활한 협업을 통해 4개월 만에 성공적으로 출시할 수 있었습니다. 이 경험을 통해, 저는 협업 능력과 시간 관리 능력의 중요성을 깨달았습니다. 앞으로도 저는 팀원들과의 적극적인 협업과 효율적인 시간 관리로 성공적인 결과를 이루기 위해 노력할 것입니다.",
        "updatedAt": "2023-06-18T14:48:31.287Z",
        "AiCapabilities": [
          "협업 능력",
          "시간 관리"
        ]
      },
      {
        "id": 24,
        "content": "상황: 개발자와 협업 역량을 쌓기 위해 IT 동아리에 들어감\n\n작업: 개발 기간이 짧아서 빠른 기간 내 런칭을 완료해야 했음.\n\n행동: 개발 기간 내에 디자인 시스템을 제작하고 개발자들과 협업하여 프로젝트를 완수했습니다. 개발자들과의 원활한 소통을 위해 주기적인 회의와 업무 분담을 진행하였으며, 문제 발생 시에는 적극적으로 해결 방안을 모색하였습니다. 또한, 개발 과정에서 발생한 변경 사항들을 유연하게 대응하여 최종적으로 빠른 기간 내에 런칭을 완료할 수 있었습니다.\n\n결과: 이러한 노력 끝에 4개월 만에 원활한 협업으로 프로젝트를 성공적으로 출시할 수 있었습니다. 유연한 커뮤니케이션과 협력은 프로젝트의 성공을 위해 중요한 역할을 했으며, 개발자와의 협업의 중요성을 더욱 깨닫게 되었습니다.\n\n키워드: 협업, 디자인 시스템 제작",
        "updatedAt": "2023-07-01T09:11:30.599Z",
        "AiCapabilities": [
          "협업",
          "디자인 시스템 제작"
        ]
      }
    ]
  }
}
```
---

## 📭 이슈 번호
#235 
---

## 🧐 의견 구하기

---

## 🙏 P.S
- 달려보자고
---

2023-07-02 06:39 UTC, stae1102 requested changes
고생하셨습니다 동현님 👍🏻 늘 작업하시는 부분이 사이즈가 꽤 크네요 감사합니다.
PR 올려주신 거 pull 받아서 테스트 해봤을 때 잘 동작하네요

다만 두 가지 의견이 있습니다!

1. 전체적으로 저희 서비스가 키워드가 종류가 다양하고 서비스가 복잡해서 명세나 주석을 추가해주시면 감사드리겠습니다! 저도 열심히 명세랑 주석 작성하도록 하겠습니다.
2. 키워드 종류가 헷갈려서 변수명을 하나로 통일할 필요가 있어 보입니다. 제가 작업한 모아보기에서의 ai 키워드와 동현님께서 작업하신 ai 추천 자기소개서 모아보기에 공통적으로 AI 역량 분석 키워드가 들어가는데, 둘이 달라서 헷갈리는 부분이 있었어요. 근데 이건 기획적으로도 한 번 통일하는 게 필요해 보입니다!

2023-07-02 06:39 UTC, stae1102 commented on src/apps/server/ai/ai.controller.ts
ai 자기소개서는 딱히 키워드에 카운팅이 없고, 자기소개서 작성 부분처럼 키워드만 뽑아내는 API가 필요 없군요?? 좋습니다

2023-07-02 06:39 UTC, stae1102 commented on src/apps/server/ai/ai.service.ts
> +    const aiResumeArr = await this.aiResumeRepository.getAiResumeByUserId(user.userId, query.aiKeyword);
query가 undefined인 경우에 TypeError가 있을 줄 알았는데 ValidationPipe 때문에 빈 객체가 가네요? 다행입니다

2023-07-02 06:39 UTC, stae1102 commented on src/apps/server/ai/dto/res/getAiResume.res.dto.ts
> +  @IsString()
IsInt나 IsNumber가 맞지 않을까요??

2023-07-02 06:39 UTC, stae1102 commented on src/apps/server/ai/dto/res/getAiResume.res.dto.ts
> +  @ApiProperty({ example: 1 })
description도 같이 적어주시면 감사드리겠습니다~

2023-07-02 06:39 UTC, stae1102 commented on src/libs/modules/database/repositories/ai-resume.repository.ts
> +class AiResumeFindManyArgs {}
사용하지 않으면 삭제해주셔도 좋겠습니다~~!

2023-07-02 06:39 UTC, stae1102 commented on src/libs/modules/database/repositories/ai-resume.repository.ts
> +    let where = <AiResumeFindManyArgs>{ userId };
Prisma 네임 스페이스에서 아마 where로 쓸 수 있는 타입을 쓸 수 있을 거예요

let where = <Prisma.AiResumeWhereInput>{ userId };

이렇게 해주셔야 더 안전한 타입으로 쓸 수 있습니다

2023-07-02 06:39 UTC, stae1102 commented on src/libs/modules/database/repositories/ai-resume.repository.ts
> +      where = { userId, AiResumeCapability: { some: { Capability: { keyword: { equals: aiKeyword } } } } };
하 프리즈마 진짜 ㅋㅋㅋㅋ lisp 쓰는 것 같아요 객체 nested가 굉장하네요 좋은 ORM을 찾아봅시다 ㅎ..

2023-07-02 06:39 UTC, stae1102 commented on src/libs/utils/array.util.ts
좋습니다~~!

2023-07-02 06:39 UTC, stae1102 commented on src/libs/modules/database/repositories/ai-resume.repository.ts
> +      where,
상황별로 where가 다르게 쓰이니까 이렇게 where를 따로 빼는 것도 좋은 방법인 것 같아요

2023-07-02 06:39 UTC, stae1102 commented on src/apps/server/ai/dto/res/getAiResume.res.dto.ts
> +  @ApiProperty({ example: ['추진력', '협업'] })
여기도 명세 써주실 수 있을까요?? 전체적으로 키워드가 많아서 백이나 프론트 모두 혼돈스러워서요!

2023-07-02 06:39 UTC, stae1102 commented on src/libs/modules/database/repositories/ai-resume.repository.ts
> +class AiResumeFindManyArgs {}
사용하시는군요~

2023-07-02 10:11 UTC, PracticeEveryday commented on src/apps/server/ai/ai.service.ts
> +    const aiResumeArr = await this.aiResumeRepository.getAiResumeByUserId(user.userId, query.aiKeyword);
네네 저도 이 쿼리에서 optional 프로퍼티는 처음 넣어 봤어여

2023-07-02 10:14 UTC, PracticeEveryday commented on src/apps/server/ai/dto/res/getAiResume.res.dto.ts
> +  @IsString()
감사합니다 :)

2023-07-02 10:14 UTC, PracticeEveryday commented on src/apps/server/ai/dto/res/getAiResume.res.dto.ts
> +  @ApiProperty({ example: 1 })
👍

2023-07-02 10:16 UTC, PracticeEveryday commented on src/libs/modules/database/repositories/ai-resume.repository.ts
> +class AiResumeFindManyArgs {}
어!! 아니에요 ㅋㅋㅋㅋ

Prisma.AiResumeWhereInput

요 고로 고쳐 놓겠습니다.

prisma의 아래 타입들이 잘 정의되어 있어 참 좋네요 :)

2023-07-02 10:16 UTC, PracticeEveryday commented on src/libs/modules/database/repositories/ai-resume.repository.ts
> +      where,
감사합니다 :)

2023-07-02 10:17 UTC, PracticeEveryday commented on src/apps/server/ai/dto/res/getAiResume.res.dto.ts
> +  @ApiProperty({ example: ['추진력', '협업'] })
👍 
 추가해 놓았습니다.

2023-07-02 10:18 UTC, PracticeEveryday commented on src/libs/modules/database/repositories/ai-resume.repository.ts
> +    let where = <AiResumeFindManyArgs>{ userId };
네네! 저도 이거 가져와지는 줄알 았는데 ㅠㅠ 위에 생겨져 있어서 놀랐네요 ㅠㅠ..

해당 타입으로 지정해 주었습니다 :)

2023-07-03 09:39 UTC, stae1102 approved these changes
고생하셔씀다

2023-07-03 11:19 UTC, merged